apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.TLS.Enabled }}"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- range $Annotation, $Value := .Values.OpenNMS.MinionGateway.IngressAnnotations }}
    {{ $Annotation | quote }}: {{ $Value | quote }}
    {{- end }}
spec:
  {{- if .Values.TLS.Enabled }}
  tls:
    - hosts:
      - "minion.{{ .Values.Host }}"
      secretName: "mionion-ssl-gateway-secret"
  {{- end }}
  rules:
    - host: "minion.{{ .Values.Host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
                port:
                  number: {{ .Values.OpenNMS.MinionGateway.GrpcPort }}
