{{- if .Values.OpenNMS.MinionSslGateway.Enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
  replicas: {{ .Values.OpenNMS.MinionSslGateway.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
    spec:
      serviceAccountName: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}-sa
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      volumes:
        - name: minion-ssl-gateway-config-volume
          configMap:
            name: minion-ssl-gateway-config
      containers:
        - name: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
          image: {{ .Values.OpenNMS.MinionSslGateway.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.MinionSslGateway.ImagePullPolicy }}
          ports:
            - name: ssl
              containerPort: {{ .Values.OpenNMS.MinionSslGateway.Port }}
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.MinionSslGateway.Resources.Limits.Cpu }}"
              memory: "{{ .Values.OpenNMS.MinionSslGateway.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.MinionSslGateway.Resources.Requests.Cpu }}"
              memory: "{{ .Values.OpenNMS.MinionSslGateway.Resources.Requests.Memory }}"
          volumeMounts:
            - name: minion-ssl-gateway-config-volume
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx-conf"
            - name: minion-ssl-gateway-config-volume
              mountPath: "/etc/nginx/minion-gateway.crt"
              subPath: "server-cert"
            - name: minion-ssl-gateway-config-volume
              mountPath: "/etc/nginx/minion-gateway.key"
              subPath: "server-key"
            - name: minion-ssl-gateway-config-volume
              mountPath: "/etc/ssl/cachain.pem"
              subPath: "trust-store"
            - name: minion-ssl-gateway-config-volume
              mountPath: "/etc/nginx/cert-passwords"
              subPath: "certificate-passwords"
{{- end }}

