## It should not need to be said, but let's say it to err on the side of safety
## THE SSL CERTIFICATES IN THIS FILE ARE NOT SECURE - DO NOT USE WITHOUT UNDERSTANDING THE INSECURITY
{{- if .Values.OpenNMS.MinionSslGateway.Enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: minion-ssl-gateway-config 
  labels:
    app: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
data:
  nginx-conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;
    
    events {
    }

    stream {
        upstream minionGateway {
            server {{ .Values.OpenNMS.MinionGatewayGrpcProxy.ServiceName }}:{{ .Values.OpenNMS.MinionGatewayGrpcProxy.Port }};
        }

        server {
            listen 443 ssl;

            proxy_pass minionGateway;
            proxy_ssl  off;
    
            ssl_alpn            h2;
            ssl_password_file   /etc/nginx/cert-passwords;
            ssl_certificate     /etc/nginx/minion-gateway.crt;
            ssl_certificate_key /etc/nginx/minion-gateway.key;
            ssl_trusted_certificate /etc/ssl/cachain.pem;
    
            ssl_verify_client       on;
            ssl_client_certificate  /etc/ssl/cachain.pem;
        }
    }
  server-cert: |
    -----BEGIN CERTIFICATE-----
    MIIFQzCCAysCFGxXxq2U71f2hZOak3r42ix3aVLVMA0GCSqGSIb3DQEBCwUAMFwx
    CzAJBgNVBAYTAkNBMQwwCgYDVQQIDANUQkQxDDAKBgNVBAcMA1RCRDEQMA4GA1UE
    CgwHT3Blbk5NUzEfMB0GA1UEAwwWaW5zZWN1cmUtb3Blbm5tcy1ocy1jYTAeFw0y
    MzAzMzAwMDI4MjFaFw0zMzAzMjcwMDI4MjFaMGAxCzAJBgNVBAYTAkNBMQwwCgYD
    VQQIDANUQkQxDDAKBgNVBAcMA1RCRDEQMA4GA1UECgwHT3Blbk5NUzEjMCEGA1UE
    Awwab3Blbm5tcy1taW5pb24tc3NsLWdhdGV3YXkwggIiMA0GCSqGSIb3DQEBAQUA
    A4ICDwAwggIKAoICAQDAe7Lekbk87n3w5XFcYKCHEkkmaLGDDqOLGtyJFCdZTy4g
    QnW4GLUy4WDmaENpm0wzT9wMtxsupl9nE7mglSlTnmTe8cm353vkjSLiegXBM4ta
    X2EQby16Bsy0GcY6Dokyy/ALiXBw8SKNxoFEEuJ8MC/XfO2bHoK6MwnubvvDDdCv
    7HhkQwTAurNwG7VSrhj9gdcNi+NDfnhWly/t9KRLk3G+4B9pq+91pIOLF14msXyt
    14AAMDxcWyytCpczq2436VGaJfE0vH47hBduX5sdh0yGM4UpDXPZSOQvrEPo+qXm
    iZ2tXv3+eOWUygOXAIv/+17Lgl1czoXmdVG+xd9L2dyCmnGaBrAvv2x8m0txB/fD
    zKw56HF+2KOTcwfN/PG8FKow6/VQ4ZcJszRQ1lGWVhEDMOvDPQh8XENfEEOh018/
    O5lfNwcXZqHkLzRDtgqYred5/n0DCb4LdLQgAlVrlA0NU3RHw644yhYY9mUBpHSP
    rkuq6MN4tQ58C3Kthn+5dPb/WqLV0v5LFt0or4iWNCCZg010c0S3QC0LKy2Dd8Ys
    z02XiLC+wVR6/1usARQccsAt/iKAS9T+Y8jNpjfNZdKUDmbmrBXNh6vCvsAERt0r
    xJ5a5ygC75Ho2XwNjLNsvmyBR/EpW4JBLOk6yE8UN6u1PylRpVao131aPAC70QID
    AQABMA0GCSqGSIb3DQEBCwUAA4ICAQAOc88YzzMxy9TWaKf98A0suSmtgCppPuj7
    fe41lJv5UK4M5s3DFFpSG7PX9ozrNkJ08LolWzH4sHHcL998RuQYudeazYWcm8cl
    WNI+cCLX0RFk6s8KBahLgmvr128oNaK9PpJkKgWqSy/nOFVvAwzNM7TozmJUl92I
    3DBRnPjc4003Q0PaoLlrCYy/g0gFXqK9zRPfP1A+wEOJwtX+VzaIjxqS0XLk3vPN
    rmdh2oHzg5cVulLfme061hwMb5AXM6/qYVr2hr/rkWuMZUF1+2dZ78sfkntf/SD4
    c2mUUayTHvpfGoMsj8PQlPqSHwTAItvEgra37vwtCuZNiSRGoStVKD1l5Qh0Xfum
    w8Y09xcLqxdm7k4LcW8BrByMTgLv521RQcqZJcHUt8c5sOO6qDaMoU2JnRdyOT0T
    2WV7HfDrYqrpZOZYcPM4p+QvBAcxP9BXj5KD9/EtMa9oNHaJkv1YNYMERifCTxoo
    rgsCZdlglNUEPxa1HS5UE7i2TrUAlTF13F80zI/roWls8PvYBNnYVIKA5h/kNVA4
    TAGiMwDAierVXAB7aKEoTdNoDMCj1MgL8T7rrOGbZ3RwQEF7lnrac9CXnhlTocTA
    P9+DQz+9mPnVhQmxJx6unidRdv3rqgPTqPLHjdh70aEF29czwfOzOvSmFixTy52u
    Rs5d8C9xEA==
    -----END CERTIFICATE-----
  server-key: |
    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIIJnDBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQI7k7wnuDI1TQCAggA
    MAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECHEC2vTpzfCLBIIJSNOtB98YtjEW
    a5mksBto60d6glujxtCrPZy1k0OICU8yH6ylPJPdYebnPc/i3RmdKAx8Y5oMHvXV
    5+n5vEEIebV0aPNWZ2l7vpPWm+cR/JhmyqzaKK9k87vo5/9BiGclGXVGpYhHJyqG
    k8oWJxns+QhNxzOdnyJ9nTHUIPU/xL6kSb3EUrzphBtwrKDuzs41jkBxoeypGLMq
    GtOhfUThDL8fiRlXtufLXJFK8FggUexS5c1QGQ6gpVtCQCzXj+lOJL3+KahQtFdp
    lZV7oFCB4/L/6vCQn0Be+FpsZ6upXUlPVYOZSasu4rd8yzamcxB24Z6soPynP8yc
    cug6MAURXjCqtMTj0IPY+xy2+dbo90Efxz6E1VlqEXjd06unnw89fl2HTDK+4Tp7
    j0jtjYPWUwFwX7aXaCnxS3uWzdgBOMf3ehT90oo0cf1vyqnGqelzsxvyedgizPzc
    PTasGfXUVHbHr71xxja+bIyJkaqjmEIqtFhABDIhLjlZ5lAykVL0IFoHGDXxJ0Gf
    vjNkecD7Xfp6q5lf2nCyF83yBatVnaFVF0j7rF2+5Gn/VCZbdb1m6i/UKZnMJaXR
    HdIhNRqQFfFPucO1myFS9bYOFbKnasSSUM/hT+EqQUA5bo7C1aBSDdQG5ZNaKP1M
    3G43XGGnLD+wATU1Fj/8eWeE7VRLCmi9mBedS3+1SQrb1D7c3La5UrnZLoaupjjz
    erStPg8/2w35Rmmt0eGrGsMeadk7nDcahmw26ACZvQ+jJAlMsZCA8ymMwmvfGaI6
    07kz+F3SiiKCwnbDr4qX9VA7rq1NDXI4AHQiSkJyB5jGhk633WsNz3SRIVtv1JGl
    dDL2BSqmjETs/jiMhK0yQaS9GAgnUioapiivMZYzAx+FahjNrT1HzamakMT0arr0
    1EME7ZvYMrcnQLi3LfJugv2bQYPNLz1QFga86ow4Z6LX4El2e80dQcacAT9fp1SM
    TwOnHVEsfFkAT/vhrDGFmxrQpqRZbRnzJhGIh45NqMs81Y0hqkR0nJC4NoCqQx9D
    XVLWNq5N2EIDm5gwDAcoPxaRK1oh4GwlanzflvEIEY3hB1VlCtw9mZribyzekjfh
    18YsTblloUybEcXPIRCZHJBtRoZtfS4/ShtAVZ9RBGDbSaqgZMOJbuw1wG/PSFX6
    Cuooc7CJlYFoJNp1c2Ygt7B5CZyAKbuI0WsumUglDQYxN8F2ABEESc6x+Gbr4uOf
    H8k4x67hU4RrdDZ28jdsKeW/uyYWCMZfA5MoXUzUch2JfxvlFsI6Q7YidT2TUzqa
    rwcynO/C/24dMvFyW40+7ZSIW5Ec8XyHyCpXHvKSq6zTBddJIMx14O8dgPsOjt0B
    TCWvtoTX0AdNhSpj8xdc3/6JVW9TFgiG9kKd7XpJr0saMs82LUzN3f1jDnLANSFW
    eRzvvE3cJSqziHH6dA1yYNYzPCjH6CJcqi6cFyjc/Ykk8ds2vw+2MIS7B6B6pFG8
    r/mQSCjzgrBFXC0DOZTEP/fWGJLdCO+drP4GhO3vZYgl13dLO72JvfU1p15g/uYJ
    VaA3A9eO45C8NM+AUP+BQN+Y1Y8eil2jZBQX8BRdjKpyxlq6e5IHM6KdSFb+0tOc
    wGjMvP/ApVSjCT7Lz5h7goQok7yKHxKmv2NBCVhimot/YOk1Y+ikRi2ILBNZUjpu
    IcQv0BH5gkOByL7RjCat+AgMovr/vZrW94Ctol1UtEqJe9F8QL1hre65vpLd33cQ
    AHlLX8gALSHOens1OyLbqvln366mdIuJUHnv63ThFsx5HPyxGYS4ADKLd8bJ11gv
    koaWENnMdZzNV3yg6KLpyU5ZKuRR9BT0a1j2B6QNGRgs6Gq1vZUc+hPptJIEesRY
    a+CCxWpOdZHw1MFIr8k34/cQ39X/O+QGpq4wo87x5jzZFTSw5oKy7I7m69HilFB4
    gSWOl1C4Q/qZSw+awl+Gl5k0ADyNmczG+7YuGxohselBhtf9VLa+SVhBvewxc0UB
    LQ36nJDdhpfQv6J9f2ood7avI2Por8I+yJgxAu63+xRd6EmkSASEbjOxJLWMC1+K
    PGWPt/lmvbOf3D2eVurG40Z+Opj5OEo1c/VP7ZSzLPWRhX+HOZjWmSRrwrzwXxy1
    C5Z4QRsPETZHZ78xaUUsz2waf9V8v4PcH35U9kp4ecYyvx8uJdJ3SuuT95+o5FyJ
    qVHCy5y4qdVJGJ02FTVub0JyrwpMKbmS23mq71VQcKGCiyp+gaR/Nwxj5ZX8lBgu
    uOL/XcZJzKfNqnLhvScgDFykSQazsFWFhsOWmimuCUHyLb5+sBWNlxxFXq65q9UL
    fdxs4kM6jDq9TIMGBaNGGioAwJDRtVlYDU69S53DhYk2CA73HKHyaX/mNwzu07XN
    mwyGnD8ywsY1TGEXEWXlP1MRGLhpQFPl31XeVo6+NWwZY4qMn/Tl8+mEIsqOlrdf
    bZRg0fSMrRkrAdTjCQYG8UNPOa8I+UUZ3tHsSZjV9QsGcwG4g09sMsfg6JGN023t
    E5CZgeN9ygWdBqXqh+HbUIBnVd5+WoDBvp5lUvycz/2rdxfUF5l69iCcZ23qbg2p
    zOhkl/vkw2A/5VqEllMPDWjou6OtnTqtX4CF3SV4ASH5+0bhExbPps4MXgkFsB9n
    X3Og+r1p7JN+RHZYUyduo46io7KwroUTFOEDEu1urWn+MV/of//Ycajlq1rboogo
    8wu7tg+KmrVY8ZPSUAtbtbjAnBQHMzMmictP9H53tQSO1dbJpndPqT2RiRXT9EZF
    Om+6TnJz0AllmLwcWyUZGO3BZ/x/828KdLPNweo+SE0Ln+m7iXuZltdvH7kN8N3T
    YX4ivH5e+PXdoxXdB4NOVGBbL6Q8AxVI7JntIK0CUFUWIJI+xuyRG3tU+GOv3sS4
    OEZuukrqjLNr70uh6sN0f5BV6OdvO8h6S2dPMfV3MMUqAGCEFhptgEu4ZHbSLnJb
    8P8Jrt9lCg3Et67vn07OpFn38sczqKtr12NeFEVb5mh1BMKvP5vaJzBvMOQijHCc
    vrgoafUzAm0mBR4SZ2rezd7JckVBWonfuoGiQ9oxSxW3UwENThbAhEw8KVNQ5YFU
    ZMIZNDHFvxb90+cjop9UVJqTYwBai1eTyIzamzWO0Zk6Szl4sgqdXGJ2pvwHe25P
    Q93ylNIaMPb+lP8AfGTQow==
    -----END ENCRYPTED PRIVATE KEY-----
  trust-store: |
    -----BEGIN CERTIFICATE-----
    MIIFmTCCA4GgAwIBAgIUTqEa9SoGNb/1yALYWuxTHA9gGdcwDQYJKoZIhvcNAQEL
    BQAwXDELMAkGA1UEBhMCQ0ExDDAKBgNVBAgMA1RCRDEMMAoGA1UEBwwDVEJEMRAw
    DgYDVQQKDAdPcGVuTk1TMR8wHQYDVQQDDBZpbnNlY3VyZS1vcGVubm1zLWhzLWNh
    MB4XDTIzMDMzMDAwMTAwNloXDTMzMDMyNzAwMTAwNlowXDELMAkGA1UEBhMCQ0Ex
    DDAKBgNVBAgMA1RCRDEMMAoGA1UEBwwDVEJEMRAwDgYDVQQKDAdPcGVuTk1TMR8w
    HQYDVQQDDBZpbnNlY3VyZS1vcGVubm1zLWhzLWNhMIICIjANBgkqhkiG9w0BAQEF
    AAOCAg8AMIICCgKCAgEAlBnrLSwxnXGHQiR4Yvp/Do26MBfg+xP2oz+xTEKsLtYT
    sI4eNawkKEERFzs5dlXC7W4HC9ycOx2LUsjggfPq4UExQdYWzW46lSfZUwBY3uK3
    1SlgUnZxvXAE1/LdD6IGRk182C+6hKCkiPoc8O7djXW8r9YwE3J0k3Q7ToAU8vc9
    iVO72XT883rijiu8V/qpEsEuXAOoUPYfccpEPzvh9HKZLTjzi65j/ioTjlvghoQd
    fcNSEvr3I9YjXaNuYCMQJLexiK3QoTbY3yORBx7IA/JiK9W/Qe632a4bbc/6fsbc
    Yr43u/QNbA7HfrUvEQTWpUv5i95teBwhjfKOzkgPG16zp1Fq8Xs/R5GbRhWP4w2y
    UZYeu7FvHjOTTEK/geWHom12PjG7oI4EaJKDbEHDI69yn6KkOdX4fMjW8usu8CJl
    gyvl8XsWNUktPwqynViAvolxan1U3e3R1oD4PSGoWfmc4+MjAzm97tm8Kz47lSzW
    uOHBlrsk4Sinnp48KiT5tINbGNyuffny8JasicPEayxDzgVc35GtnTuM609eqyMJ
    NAt8df+th/0AwekMZG/PfmkVIDXpI3v50NAs5Il8z6+2hAz6D+be3tQYpmvPNFiZ
    GaIdAw259NmYmYcZkMMDddzz6fSrL20sW31vRwfkyebYKgyFtPHmwIpOjqcsVCkC
    AwEAAaNTMFEwHQYDVR0OBBYEFNOG81pCLrmlpfGmSp5zAfW+ZJCcMB8GA1UdIwQY
    MBaAFNOG81pCLrmlpfGmSp5zAfW+ZJCcMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
    hvcNAQELBQADggIBAF9PhegKzaqOuIilBWhr/+ZvZcBODyciq/5YQg2nXwv7sx68
    GFSSlK1//NUjy+3pArVyFtC0GG0gn9w4bdVPwvANBiNs5Zrg+kgiUQSP/IThEEXI
    4neEeO5oJK/pMn4pAUEECldXCwsyUe2RqxSc7F7m3FHytTh8K12dd21ovfvZNKNF
    vFEijED4i1GWi4S5+yi2PVWNvd233MQa1CRZnjt4sm4R0YWotxwJckX0Rjz5fsFc
    u0YzWkZy6wOuR3nhnR1drJIDU/FjIRBUCMhsVaxadfcsCWJ+tZsNneiBfKrI+7KY
    Q6w/iNb6lt7wLrvEvUBuBupoSOf3apkJEM/J6fEfTqrbbs0MIqhmPQ0lWCgrGGw1
    buC6L2JknE5/xVJM/41oVBydZ98aiRrVjYdXzfCD2mETuS1tvgYpxfRN1AnDaCHF
    RhgsircPONmJXpP+Nv+GM+2XjmXuKVO3lzTIum9GzmHDnZgY2xUGpG/KhEYSP5kJ
    jsxTTFJLSXg58kcTT6Bl5J6tZUVun8+edU6tsnAlpq2YVZ50QoiGlTVFOnKZZMCm
    RpLHffaao1IspT6I0nQLkcPdg7CUhrAaBdRkgPy1fKnU92JLn1FvPF9bxQzZkzYe
    0T349NxOxpmBg1K4WoHBZK8snr76BbMbDBvbIN7fv4JQaEWGSaW0jVXoz8lo
    -----END CERTIFICATE-----
  certificate-passwords: |
    passw0rd
{{- end }}
