{{- if .Values.OpenNMS.MinionSslGateway.Enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.OpenNMS.MinionSslGateway.ServiceName }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
