apiVersion: k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: local-instance
spec:
  allowedUsers: []
  host: onmshs
  namespace: local-instance
  deployOnly: true
  core:
    image: opennms/horizon-stream-core
    cpu: "0"
    mem: "0"
  api:
    image: opennms/horizon-stream-rest-server
    cpu: "0"
    mem: "0"
  ui:
    image: opennms/horizon-stream-ui
    cpu: "0"
    mem: "0"
  postgres:
    image: postgres:13.3-alpine
  credentials:
    adminPassword: admin
    userPassword: passw0rd
