# nonk8s
## LOCAL PORT ASSIGNMENTS (note internal ports use the native port number)
##	xx = service/container
##	xx080 = HTTP
##	xx089 = GRPC
##	xx022 = SSH
##	xx025 = SMTP (mail)
##	xx050 = JAVA DEBUG
##	xx054 = POSTGRES
##	xx090 = KAFKA
##
## 11 = horizon-stream-core
## 12 = horizon-stream-minion
## 13 = horizon-stream-api
## 14 = api-gateway
## 15 = horizon-stream-notification
## 16 = horizon-stream-minion-gateway
## 17 = horizon-stream-ui
## 18 = grafana
## 19 = prometheus
## 21 = prometheus-pushgateway
## 22 = mail-server
## 23 = zookeeper
## 24 = kafka
## 25 = postgres
## 26 = keycloak
## 27 = minion (classic)
##

apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: horizon-stream
requires:
  - configs: ["keycloak-operator"]
  - configs: ["parent-pom"]
    path: parent-pom/skaffold.yaml
  - configs: ["shared-lib"]
    path: shared-lib/skaffold.yaml
  - configs: ["horizon-stream-ui"]
    path: ui/skaffold.yaml
  - configs: ["minion-gateway"]
    path: minion-gateway/skaffold.yaml
profiles:
  - name: prod
build:
  artifacts:
  - image: opennms/horizon-stream-core
    context: platform
    custom:
      buildCommand: "mvn install -Pbuild-docker-images-enabled -DskipTests=$SKIP_TEST -Ddocker.image=$IMAGE -Ddocker.skipPush={{ .PUSH_IMAGE | not }}"
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**",
          "**/dependency-reduced-pom.xml" # generated by maven-shade-plugin, these cause file watching to break when running `skaffold debug`
        ]
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-minion
    context: minion
    custom:
      buildCommand: "mvn install -Pbuild-docker-images-enabled -DskipTests -Ddocker.image=$IMAGE -Ddocker.skipPush={{ .PUSH_IMAGE | not }}"
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**", 
          "**/dependency-reduced-pom.xml" # generated by maven-shade-plugin, these cause file watching to break when running `skaffold debug`
        ]
    requires:
      - image: shared_lib
      - image: parent-pom
        alias: unused_parent
  - image: opennms/horizon-stream-api
    context: rest-server
    jib: {}
    sync:
      auto: true
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-notification
    context: notifications
    jib: {}
    sync:
      auto: true
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-keycloak-dev
    context: keycloak-ui
    sync:
      infer:
        - "themes/**"
    docker:
      dockerfile: Dockerfile
  - image: opennms/grafana-dev
    context: grafana
    docker:
      dockerfile: Dockerfile

portForward:
  - resourceType: deployment
    resourceName: my-horizon-stream-api
    port: 9090 # HTTP
    localPort: 13080
  - resourceType: deployment
    resourceName: my-horizon-stream-api
    port: 5005 # Debug
    localPort: 13050
  - resourceType: deployment
    resourceName: my-horizon-stream-notification
    port: 8080 # HTTP
    localPort: 15080
  - resourceType: deployment
    resourceName: my-horizon-stream-notification
    port: 5005 # Debug
    localPort: 15050
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 8181 # HTTP
    localPort: 11080
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 8101 # SSH
    localPort: 11022
  - resourceType: deployment
    resourceName: my-horizon-stream-core
    port: 5005 # Debug
    localPort: 11050
  - resourceType: deployment
    resourceName: my-horizon-stream-minion
    port: 8181 # HTTP
    localPort: 12080
  - resourceType: deployment
    resourceName: my-horizon-stream-minion
    port: 8102 # SSH
    localPort: 12022
  - resourceType: deployment
    resourceName: my-horizon-stream-minion
    port: 5005 # Debug
    localPort: 12050
  - resourceType: deployment
    resourceName: my-keycloak
    port: 8080 # HTTP
    localPort: 26080
  - resourceType: deployment
    resourceName: my-minion
    port: 8201 # SSH
    localPort: 27022
  - resourceType: deployment
    resourceName: api-gateway
    port: 80 # HTTP
    localPort: 14080
  - resourceType: deployment
    resourceName: minion-gateway
    port: 8080 # HTTP
    localPort: 16080
  - resourceType: deployment
    resourceName: minion-gateway
    port: 8990 # GRPC
  - resourceType: deployment
    resourceName: minion-gateway
    port: 5005 # Debug
    localPort: 16050
  - resourceType: deployment
    resourceName: horizon-mail-server
    port: 8025 # HTTP
    localPort: 22080
  - resourceType: deployment
    resourceName: horizon-mail-server
    port: 1025 # SMTP
    localPort: 22025
  - resourceType: deployment
    resourceName: my-postgres
    port: 5432 # Postgres
    localPort: 25054
  - resourceType: deployment
    resourceName: prometheus
    port: 9090 # prometheus tcp
    localPort: 19080
  - resourceType: deployment
    resourceName: prometheus-pushgateway
    port: 9091 #prometheus-pushgateway tcp
    localPort: 21080
  - resourceType: deployment
    resourceName: grafana
    port: 3000 #grafana HTTP
    localPort: 18080
  - resourceType: deployment
    resourceName: my-kafka
    port: 59092 # kafka tcp local client port
    localPort: 24090
deploy:
  kubectl:
    manifests:
      - dev/kubernetes.kafka.yaml

---

apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: keycloak-operator
deploy:
  kubectl:
    manifests:
      - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
      - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
      - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.0/kubernetes/kubernetes.yml
