apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  name: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.Postgres.Replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.Postgres.ServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.Postgres.ServiceName }}
        role: master
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "{{ .Values.NodeRestrictions.Key }}"
                operator: In
                values:
                - {{ .Values.NodeRestrictions.Value }}
      {{- end }}
      volumes:
        - name: postgres-volume
        - name: postgres-initial-script
          secret:
            secretName: postgres-initial-sql
      containers:
        - name: {{ .Values.Postgres.ServiceName }}
          image: {{ .Values.Postgres.Image }}
          imagePullPolicy: {{ .Values.Postgres.ImagePullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminPwd
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-volume
            - mountPath: "/docker-entrypoint-initdb.d/postgres.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.keycloak.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.keycloak.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.inventory.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.inventory.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.alarm.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.alarm.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.notification.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.notification.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.grafana.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.grafana.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.events.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.events.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.datachoices.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.datachoices.initial.script.sql"
            - mountPath: "/docker-entrypoint-initdb.d/postgres.minion_gateway.initial.script.sql"
              name: postgres-initial-script
              subPath: "postgres.minion_gateway.initial.script.sql"
