apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Release.Namespace }}
data:
  adminUser: "{{ "postgres" | b64enc }}"
  adminPwd: "{{ .Values.Postgres.AdminPassword | b64enc }}"
  opennmsUser: "{{ "opennms" | b64enc }}"
  opennmsPwd: "{{ .Values.Postgres.OpenNMSPassword | b64enc }}"
  keycloakUser: "{{ "keycloak" | b64enc }}"
  keycloakPwd: "{{ .Values.Postgres.KeycloakPassword | b64enc }}"
  inventoryUser: "{{ "inventory" | b64enc }}"
  inventoryPwd: "{{ .Values.Postgres.InventoryPassword | b64enc }}"
  alarmUser: "{{ "alarm" | b64enc }}"
  alarmPwd: "{{ .Values.Postgres.AlarmPassword | b64enc }}"
  notificationUser: "{{ "notification" | b64enc }}"
  notificationPwd: "{{ .Values.Postgres.NotificationPassword | b64enc }}"
  grafanaUser: "{{ "grafana" | b64enc }}"
  grafanaPwd: "{{ .Values.Postgres.GrafanaPassword | b64enc }}"
  eventsUser: "{{ "events" | b64enc }}"
  eventsPwd: "{{ .Values.Postgres.EventsPassword | b64enc }}"
  dataChoicesUsr: "{{ "datachoices" | b64enc }}"
  dataChoicesPwd: "{{ .Values.Postgres.DataChoicesPassword | b64enc }}"
  minionGatewayUsr: "{{ "minion_gateway" | b64enc }}"
  minionGatewayPwd: "{{ .Values.Postgres.MinionGatewayPassword | b64enc }}"
type: Opaque
