#create
mutation CreateLocation($location: MonitoringLocationCreateInput!) {
  createLocation(location: $location){
    id
    location
    address
    longitude
    latitude
    tenantId
  }
}

#update
mutation UpdateLocation($location: MonitoringLocationUpdateInput) {
  updateLocation(location: $location) {
    id
    location
    address
    longitude
    latitude
    tenantId
  }
}

#delete
mutation DeleteLocation($id: Long!) {
  deleteLocation(id: $id)
}
