apiVersion: v1
kind: ConfigMap
metadata:
  name: snmpd-config
  labels:
    app: snmpd
data:
  snmpd.conf: |
    com2sec notConfigUser  default       public
    
    group   notConfigGroup v1           notConfigUser
    group   notConfigGroup v2c           notConfigUser
    
    view    systemview    included   .1.3.6.1.2.1.1
    view    systemview    included   .1.3.6.1.2.1.25.1.1
    view    all           included   .1
    
    access  notConfigGroup ""      any       noauth    exact  all none none

    com2sec local     localhost       public
    com2sec mynetwork NETWORK/24      public
      
    group MyRWGroup  any        local
    group MyROGroup  any        mynetwork
    
    access MyROGroup ""      any       noauth    0      all    none   none
    #access MyRWGroup ""      any       noauth    0      all    all    all
    
    syslocation Unknown (edit /etc/snmp/snmpd.conf)
    syscontact Root <root@localhost> (configure /etc/snmp/snmp.local.conf)
    dontLogTCPWrappersConnects yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmpd
  labels:
    app: snmpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmpd
  template:
    metadata:
      labels:
        app: snmpd
      annotations:
        kubectl.kubernetes.io/default-container: "snmpd"
    spec:
      volumes:
        - name: snmpd-conf-volume
          configMap:
            name: snmpd-config
      containers:
      - name: snmpd
        image: polinux/snmpd
        ports:
        - containerPort: 161
        volumeMounts:
          - mountPath: "/etc/snmp/snmpd.conf"
            subPath: "snmpd.conf"
            name: snmpd-conf-volume
            readOnly: true
