apiVersion: k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: local-instance
spec:
  allowedUsers: []
  host: onmshs
  httpPort: 80
  httpsPort: 443
  namespace: local-instance
  tlsEnabled: true
  deployOnly: true
  core:
    image: opennms/lokahi-core
    cpu: "0"
    mem: "0"
  api:
    image: opennms/lokahi-rest-server
    cpu: "0"
    mem: 500Mi
  ui:
    image: opennms/lokahi-ui
    cpu: "0"
    mem: 100Mi
  minion:
    image: opennms/lokahi-minion
    cpu: "0"
    mem: 1000Mi
  minionGateway:
    image: opennms/lokahi-minion-gateway
    cpu: "0"
    mem: 500Mi
  notification:
    image: opennms/lokahi-notification
    cpu: "0"
    mem: 100Mi
  inventory:
    image: opennms/lokahi-inventory
  metricsProcessor:
    image: opennms/lokahi-metrics-processor
  events:
    image: opennms/lokahi-events
  datachoices:
    image: opennms/lokahi-datachoices
  keycloak:
    image: opennms/lokahi-keycloak
  grafana:
    image: opennms/lokahi-grafana
  postgres:
    image: postgres:14.5-alpine
  credentials:
    adminPassword: admin
    userPassword: passw0rd
