apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.OpenNMS.MetricsProcessor.Replicas }}
  selector:
    matchLabels:
      run: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  template:
    metadata:
      labels:
        appdomain: opennms
        run: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        # roll the deployment when the Spring boot environment variable configmap changes
        checksum/spring-boot-env-configmap: {{ include (print $.Template.BasePath "/opennms/spring-boot-env-configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: "{{ .Values.OpenNMS.MetricsProcessor.ServiceName }}"
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      volumes:
        - name: spring-boot-app-config-volume
          configMap:
            name: spring-boot-app-config
      containers:
        - name: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
          image: {{ .Values.OpenNMS.MetricsProcessor.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.MetricsProcessor.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:agent/opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.OpenNMS.global.kafkaClient.bootstrapServers }}"
            - name: GRPC_FLOW_INGESTOR_URL
              value: "{{ .Values.OpenNMS.MetricsProcessor.FlowIngestorUrl }}"
            - name: GRPC_FLOW_TLS_ENABLED
              value: "{{ .Values.OpenNMS.MetricsProcessor.FlowTlsEnabled }}"
            - name: CORTEX_WRITE_URL
              value: {{ .Values.CortexClient.Protocol }}://{{ .Values.CortexClient.HostWrite }}:{{ .Values.CortexClient.PortWrite }}{{ .Values.CortexClient.PathWrite }}
            {{- include "deployment.env" .Values.OpenNMS.MetricsProcessor | nindent 12 }}
          envFrom:
          - configMapRef:
              name: spring-boot-env
          {{- include "kafkaSecretFrom" .Values.OpenNMS.MetricsProcessor | indent 10 }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: spring-boot-app-config-volume
              mountPath: "/app/config"
      {{- if .Values.OpenNMS.MetricsProcessor.PrivateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
