#!/bin/bash

set -e

echo "=== GENERATE CA CERT"
openssl req \
	-new \
	-newkey rsa:4096 \
	-days 3650 \
	-nodes \
	-x509 \
	-subj "/C=CA/ST=TBD/L=TBD/O=OpenNMS/CN=insecure-opennms-hs-ca" \
	-keyout CA.key \
	-out CA.cert

