# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: shared-lib
build:
  local:
    push: false
  artifacts:
  - image: shared-lib
    custom:
      # shared-lib builds only a jar, not an image.
      # Skaffold requires that artifacts produce images. This is a workaround that builds a dummy image.
      buildCommand: |
        mvn clean install &&
        echo 'FROM scratch' | docker build -t $IMAGE -
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**"
        ]
