# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: shared-lib
requires:
  - configs: ["parent-pom"]
    path: ../parent-pom/skaffold.yaml
build:
  local:
    push: false
  artifacts:
  - image: shared_lib # use an underscore, so we can reference this in other Skaffold artifacts without an alias
    custom:
      # shared-lib builds only a jar, not an image.
      # Skaffold requires that artifacts produce images. This is a workaround that builds a dummy image.
      buildCommand: |
        mvn clean install -DskipTests=$SKIP_TEST &&
        printf 'FROM scratch\nCMD \"Dummy Image Started\"' | docker build -t $IMAGE -
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**"
        ]
    requires:
      - image: parent-pom
        alias: unused
