apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.Inventory.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.Inventory.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.Inventory.ServiceName }}
  replicas: {{ .Values.OpenNMS.Inventory.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.Inventory.ServiceName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.OpenNMS.Inventory.Port }}"
        prometheus.io/path: "/actuator/prometheus"
        # roll the deployment when the Spring boot environment variable configmap changes
        checksum/spring-boot-env-configmap: {{ include (print $.Template.BasePath "/opennms/spring-boot-env-configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: "{{ .Values.OpenNMS.Inventory.ServiceName }}"
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      volumes:
        - name: spring-boot-app-config-volume
          configMap:
            name: spring-boot-app-config
      containers:
        - name: {{ .Values.OpenNMS.Inventory.ServiceName }}
          image: {{ .Values.OpenNMS.Inventory.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Inventory.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:agent/opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.OpenNMS.Inventory.DbHost }}:5432/{{ .Values.OpenNMS.Inventory.DbName }}?currentSchema={{ .Values.OpenNMS.Inventory.DbSchemaName }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: inventoryUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: inventoryPwd
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.OpenNMS.global.kafkaClient.bootstrapServers }}"
            - name: KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.ServiceName }}:8080/auth/"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.Keycloak.RealmName }}"
            - name: INVENTORY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: encryptionKey
                  name: {{ .Values.OpenNMS.Inventory.ServiceName }}-encryption-key
            {{- include "deployment.env" .Values.OpenNMS.Inventory | nindent 12 }}
          envFrom:
          - configMapRef:
              name: spring-boot-env
          {{- include "kafkaSecretFrom" .Values.OpenNMS.Inventory | indent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.OpenNMS.Inventory.Port }}
            - name: grpc
              containerPort: {{ .Values.OpenNMS.Inventory.GrpcPort }}
          volumeMounts:
            - name: spring-boot-app-config-volume
              mountPath: "/app/config"
      {{- if .Values.OpenNMS.Inventory.PrivateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
