name: 'Build and test core'
description: 'This implements unit and built-time integration tests on core, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'

runs:
  using: "composite"
  steps:
    - name: global data
      run: |
        echo "Testing actions - " ${{ inputs.dir-location }}
        echo "test 3 - action core" >> tmp.test

        cd ${{ inputs.dir-location }}
        # Keep the input arg of the dir, if the process is the same for each
        # core, rest-server, and ui, we can make this like a generic function.

        # IMPORTANT: Check the .circleci/ original build.

        # Simple build - no Integration Tests
        mvn clean install
        # For testing the pipeline, just run this without tests to get the
        # publish working with releasing working correctly. The test takes
        # 5mins roughly.
        # Release on 0.0.0 for now.

        # Full build, including docker image creation and Integration Tests
        #mvn -Prun-it clean install
        # Ran test, worked, took about 5mins.

        # How do we trigger the unit tests?

        #docker images
        # The image, opennms-horizon-application-it-image, is just for the
        # integration tests, ignore.  

        # Save the image as a file to be published.
        docker save -o horizon-stream-core.tar opennms/horizon-stream-core:local

      shell: bash
