{{- if .Values.Prometheus.Enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Prometheus.ServiceName }}
  labels:
    app: {{ .Values.Prometheus.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.Prometheus.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Prometheus.ServiceName }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.Prometheus.ServiceName }}
      annotations:
        kubectl.kubernetes.io/default-container: "{{ .Values.Prometheus.ServiceName }}"
    spec:
      serviceAccountName: prometheus-sa
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "{{ .Values.NodeRestrictions.Key }}"
                    operator: In
                    values:
                      - {{ .Values.NodeRestrictions.Value }}
      {{- end }}
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config-map
      containers:
        - name: {{ .Values.Prometheus.ServiceName }}
          image: {{ .Values.Prometheus.Image }}
          ports:
            - containerPort: {{ .Values.Prometheus.Port }}
          resources:
            limits:
              cpu: {{ .Values.Prometheus.Resources.Limits.Cpu }}
              memory: {{ .Values.Prometheus.Resources.Limits.Memory }}
            requests:
              cpu: {{ .Values.Prometheus.Resources.Requests.Cpu }}
              memory: {{ .Values.Prometheus.Resources.Requests.Memory }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: "/etc/prometheus/prometheus.yml"
              subPath: "prometheus.yml"
          args:
            # Keep the image built-in arguments (anyone know a future-proof way?)
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
            # Add the prefix /prometheus to the URLs so the paths going through the ingress will work
            - --web.external-url=/prometheus
{{- end }}
