name: 'Build and test Operator'
description: 'This implements unit and built-time integration tests on the Operator, dir platform.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'operator'

runs:
  using: "composite"
  steps:
    - name: unit-test
      run: |
        cd ${{ inputs.dir-location }}

        make unit-test
      
      shell: bash

    - name: build-image
      run: |

        cd ${{ inputs.dir-location }}

        # When there are tests to run, put those here.

        # Create the docker image.
        make local-docker

      shell: bash
  
