mutation AcknowledgeAlerts($alertId: Long!) {
  acknowledgeAlert(id: $alertId) {
    acknowledged
    databaseId
  }
}
mutation ClearAlerts($alertId: Long!) {
  clearAlert(id: $alertId) {
    databaseId
    clearKey
  }
}
