fragment AlertsList on Query {
  alertsList {
    id
    name
    severity
    cause
    duration
    nodeType
    date
    time
    isAcknowledged
    description
  }
}

query Alerts {
  ...AlertsList
}

# fetch search alert list
