name: 'Build and test Minion'
description: 'This implements unit and built-time integration tests on minion, dir minion.'
inputs:
  dir-location:
    description: 'The dir containing the change.'
    required: true
    default: 'none'
  enable-sonar-scan:
    description: 'Enables code scanning with SonarCloud.'
    required: true
  github-token:
    description: 'GITHUB_TOKEN secret for the workflow so SonarCloud can get PR information. Required if enable-sonar-scan is true.'
    required: false
  sonar-token:
    description: 'SONAR_TOKEN secret to authenticate job with SonarCloud. Required if enable-sonar-scan is true.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache SonarCloud packages
      if: ${{ inputs.enable-sonar-scan == 'true' }}
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-${{ runner.arch }}-sonar

    - name: global data
      if: ${{ inputs.enable-sonar-scan == 'true' }}
      run: |

        mvn -Pcoverage verify -Ddocker.image=opennms/horizon-stream-minion:local -Ddocker.skipPush=true \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY

      shell: bash
      working-directory: minion
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_PROJECT_KEY: 'opennms_horizon-stream_minion'

    - name: global data
      if: ${{ inputs.enable-sonar-scan == 'false' }}
      run: |

        mvn verify -Ddocker.image=opennms/horizon-stream-minion:local -Ddocker.skipPush=true

      working-directory: minion
      shell: bash
