# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: horizon-stream-ui
build:
  local:
    useBuildkit: true
  artifacts:
  - image: opennms/horizon-stream-ui
    sync:
      manual: # Inferred file sync is limited for multi-stage builds, use manual sync.
        - src: 'src/**'
          dest: .
        - src: 'public/**'
          dest: .
        - src: 'tests/**'
          dest: .
        - src: '.env'
          dest: .
        - src: '.env.*'
          dest: .
        - src: 'index.html'
          dest: .
        - src: '*.ts'
          dest: .
    docker:
      dockerfile: Dockerfile
      target: development
portForward:
  - resourceType: deployment
    resourceName: opennms-ui
    port: 80 # nginx HTTP
    localPort: 17080
profiles:
  - name: prod
    build:
      artifacts:
      - image: opennms/horizon-stream-ui
        docker:
          dockerfile: Dockerfile
