apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.MinionGateway.HttpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.OpenNMS.MinionGateway.GrpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.OpenNMS.MinionGateway.IgniteClientPort }}
      protocol: TCP
      name: ignite-client
  selector:
    run: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
---
