apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}-config-map
  labels:
    app: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
data:
  minion-config.yaml: |
    id: "minion-01"
    location: "Default"

    karaf:
      shell:
        ssh:
          host: "0.0.0.0"

    ipc:
      grpc:
        host: "{{ .Values.OpenNMS.Core.ServiceName }}"
        port: "{{ .Values.OpenNMS.Core.GrpcPort }}"

    netmgt:
      syslog:
        syslog.listen.interface: "0.0.0.0"
        syslog.listen.port: {{ .Values.OpenNMS.Minion.SyslogPort }}

      traps:
        trapd.listen.interface: "0.0.0.0"
        trapd.listen.port: {{ .Values.OpenNMS.Minion.SnmpPort }}
