apiVersion: k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: opennms-instance
spec:
  host: onmshs
  httpPort: 80
  httpsPort: 443
  namespace: opennms-instance
  tlsEnabled: false
  deployOnly: true
  updateConfig:
    mode: manual
    update: none
  api:
    image: opennms/horizon-stream-rest-server
    cpu: "0"
    mem: 500Mi
  ui:
    image: opennms/horizon-stream-ui
    cpu: "0"
    mem: 100Mi
  minion:
    image: opennms/horizon-stream-minion
    cpu: "0"
    mem: 1000Mi
  minionGateway:
    image: opennms/horizon-stream-minion-gateway
    cpu: "0"
    mem: 500Mi
  minionSslGateway:
    image: opennms/horizon-stream-minion-gateway
    cpu: "0"
    mem: 200Mi
  inventory:
    image: opennms/horizon-stream-inventory
    cpu: "0"
    mem: 100Mi
  alert:
    image: opennms/horizon-stream-alert
    cpu: "0"
    mem: 100Mi
  notification:
    image: opennms/horizon-stream-notification
    cpu: "0"
    mem: 100Mi
  metricsProcessor:
    image: opennms/horizon-stream-metrics-processor
    cpu: "0"
    mem: 256Mi
  events:
    image: opennms/horizon-stream-events
    cpu: "0"
    mem: 100Mi
  datachoices:
    image: opennms/horizon-stream-datachoices
    cpu: "0"
    mem: 100Mi
  keycloak:
    image: opennms/horizon-stream-keycloak
  grafana:
    image: opennms/horizon-stream-grafana
  postgres:
    image: postgres:14.5-alpine
  credentials:
    adminPassword: admin
    userPassword: passw0rd
